### PR TITLE
Handle type aliases better

### LINKED ISSUE #2: Handle generics better
Right now the binding generator attempts to convert generic types in Rust to templates in the .h file. I thought this would work, but it doesn't because the .h file is extern "C" (as opposed to C++) and so templates are disallowed. We need to figure out a better way to convert generic types into concrete types.

### PR DESCRIPTION
**Pull request by eqrion**
This isn't the cleanest patch. `main.rs` could use a refactor, things are getting stringly typed.

Should fix #2

### CODE REVIEW

**Comment by staktrace** [comment]
Maybe I didn't do it right but when I run this against webrender_bindings the output includes stuff like this:

`typedef unknown BareFn(BareFnTy { unsafety: Normal, abi: None, lifetimes: [], inputs: [BareFnArg { name: None, ty: Ptr(MutTy { ty: Path(None, Path { global: false, segments: [PathSegment { ident: Ident("c_void"), parameters: AngleBracketed(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), mutability: Mutable }) }, BareFnArg { name: None, ty: Path(None, Path { global: false, segments: [PathSegment { ident: Ident("ExternalImageId"), parameters: AngleBracketed(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }) }], output: Ty(Path(None, Path { global: false, segments: [PathSegment { ident: Ident("WrExternalImageStruct"), parameters: AngleBracketed(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] })), variadic: false }) LockExternalImageCallback;`

Is that intended? This looks like function pointer stuff. Also it doesn't seem to be generating the generic types properly? It's just stripping the type parameterization from what was there before. Full diff at https://gist.github.com/staktrace/17d2f1574fed8095b186a42a8a94b50a

**Comment by eqrion** [comment]
The typedefs with unknowns is a problem coming from not handling fn ptrs. We shouldn't be outputting this junk though, we should just skip it if we don't support it.

As for the generics, do you have type aliases defined for the generics?

I think we'll need a `type WrFloatSideOffsets = WrSideOffsets<f32>`, and then use WrFloatSideOffsets. If you just use WrSideOffsets, then the generic WrSideOffsets structure will be used which doesn't work. The type alias will generate a specialized structure from the generic struct with the `T`s replaced. It's not great, and is fragile, but it works.

**Comment by eqrion** [comment]
I should add that I think I have a good idea how to refactor wr-binding, that should make the implementation of this simpler and better and make supporting opaque pointers easier. I have the beginnings of a patch.

If it doesn't take long I could squash that patch with these ones.

**Comment by staktrace** [comment]
Ah, I was missing the type aliases. That makes sense. I'm happy to just merge these patches as you write them. Honestly I'm not going to spend much time reviewing them since the generated output is the important thing - as long as that looks sane we should be fine.

**Pull request merged**
